[Build]
# TODO: should be BOS_DEVICE=generic
Environment=
        BOS_DEVICE=qemu

[Distribution]
Architecture=x86-64
Repositories=
        contrib
        non-free
        non-free-firmware

[Content]
Packages=
        linux-image-amd64
        firmware-linux
        firmware-linux-nonfree
        qemu-guest-agent

KernelCommandLine=console=ttyS0

[Runtime]
Console=gui
RAM=6G # https://github.com/systemd/systemd/issues/35026
CPUs=4
TPM=yes
Firmware=uefi
RuntimeSize=20G
