[Content]
Packages=
        bengalos-phosh
        # For cellbroadcast support
        gir1.2-modemmanager-1.0/experimental
        libmm-glib0/experimental
        modemmanager/experimental

RemovePackages=
        gnome-software
        gnome-software-plugin-deb
        gnome-user-docs
        # For x11 only, pulled in by uim
        im-config
        packagekit
        # Drop unneeded uim modules
        uim-fep
        uim-gtk2.0
        uim-gtk2.0-immodule
        uim-gtk3
        uim-gtk3-immodule
        uim-qt5
        uim-qt5-immodule
        uim-qt6
        uim-qt6-immodule
        uim-xim
        usbmuxd
        x11-xserver-utils
