[Content]
Packages=
        bengalos-phosh

RemovePackages=
        gnome-software
        gnome-software-plugin-deb
        gnome-user-docs
        packagekit
        x11-xserver-utils
        usbmuxd
        # Drop unneeded uim modules
        uim-fep
        uim-gtk2.0
        uim-gtk2.0-immodule
        uim-gtk3
        uim-gtk3-immodule
        uim-qt5
        uim-qt5-immodule
        uim-qt6
        uim-qt6-immodule
        uim-xim
