---

stages:
  - build
  - test
  - publish
  - cleanup

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  PHOSH_IMAGE_BRANCH: main
  PHOSH_IMAGE_UPLOAD_OPTS: --verbose
  LINT_DEPS: black flake8 markdownlint shellcheck mypy

default:
  timeout: 36 hours
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

.import_gpg_key: &import_gpg_key
  - GNUPGHOME=$(mktemp -d)
  - export GNUPGHOME
  - echo "$SIGNING_KEY" | base64 -d | gpg --batch --import
  - gpg --list-keys $BENGALOS_SIGNING_KEY

.clear_gpg_key: &clear_gpg_key
  - rm -rf $GNUPGHOME

build:dev:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    ARCH: amd64
    FLAVOR: development
  script:
    - XDG_CACHE_HOME=~/.cache make clean bengalos
    - |
      if [ -n "${PHOSH_IMAGE_HOST}" ] && \
         [ -n "${PHOSH_IMAGE_UPLOAD}" ] && \
         [ "${CI_COMMIT_BRANCH}" = "${PHOSH_IMAGE_BRANCH}" ]; then
        ls -lh build-${ARCH}-${FLAVOR}/BengalOS_*
        time make IMAGE_HOST="${PHOSH_IMAGE_HOST}" upload
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi

build:immutable:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    ARCH: amd64
    FLAVOR: immutable
    AWS_ACCESS_KEY_ID: $PUSH_KEY
    AWS_SECRET_ACCESS_KEY: $PUSH_SECRET
    MKOSI_SECURE_BOOT_CRT: $SECURE_BOOT_CRT
    MKOSI_SECURE_BOOT_KEY: $SECURE_BOOT_KEY
    BENGALOS_SIGNING_KEY: $SIGNING_KEY_ID
  before_script:
    - *import_gpg_key
  script:
    - |
      XDG_CACHE_HOME=~/.cache make clean
      mkdir -p build-${ARCH}-${FLAVOR}
      # Secure boot certificate
      echo "$MKOSI_SECURE_BOOT_CRT" > build-${ARCH}-${FLAVOR}/mkosi.crt
      openssl x509 -in "build-${ARCH}-${FLAVOR}/mkosi.crt" -noout -text
      # Secure boot signing key
      UMASK=$(umask) && umask 077
      echo "$MKOSI_SECURE_BOOT_KEY" | base64 -d > build-${ARCH}-${FLAVOR}/mkosi.key
      umask ${UMASK}
      XDG_CACHE_HOME=~/.cache make bengalos
    - |
      if [ -n "$AWS_ENDPOINT_URL" ]; then
        time ./helpers/pack.sh
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi
  after_script:
    - *clear_gpg_key
    - rm -f build-${ARCH}-${VARIANT}/mkosi.key
  artifacts:
    paths:
      - build-amd64-immutable/*/hash

test:immutable:nightly:amd64:
  stage: test
  tags: ["phosh-images"]
  resource_group: phoshimages
  needs:
    - job: build:immutable:nightly:amd64
      artifacts: true
  script:
    - |
      rm -f *.qcow2
      HASH=$(awk '{ print $1 }' build-amd64-immutable/*/hash | head -n 1)
      echo "Testing ${HASH}"
      time ./helpers/get-qcow2.sh --hash "${HASH}"
      helpers/smoke-test-vm.sh --name "${HASH}" --disk *.qcow2
  artifacts:
    when: always
    paths:
      - build-amd64-immutable/*/hash
      - "smoke-*.png"

publish:immutable:nightly:amd64:
  stage: publish
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    AWS_ACCESS_KEY_ID: $BLESS_KEY
    AWS_SECRET_ACCESS_KEY: $BLESS_SECRET
    BENGALOS_SIGNING_KEY: $SIGNING_KEY_ID
  needs:
    - job: test:immutable:nightly:amd64
      artifacts: true
  before_script:
    - *import_gpg_key
  script:
    - |
      HASH=$(awk '{ print $1 }' build-amd64-immutable/*/hash | head -n 1)
      echo "Blessing ${HASH}"
      helpers/bless.sh --hash "${HASH}"
  after_script:
    - *clear_gpg_key
    - rm -f build-${ARCH}-${VARIANT}/mkosi.key
  artifacts:
    paths:
      - build-amd64-immutable/*/hash
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "BengalOS-team/bengalos-recipes" && $CI_PIPELINE_SOURCE == "schedule"'

lint:
  stage: test
  needs: []
  image: 'godiug/website:v0.0.2025-09-14'
  script:
    - apt-get update
    - apt-get -y install $LINT_DEPS
    - make lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.cleanup-blessed:
  stage: cleanup
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    AWS_ACCESS_KEY_ID: $BLESS_KEY
    AWS_SECRET_ACCESS_KEY: $BLESS_SECRET
  script:
    - helpers/cleanup-blessed-builds.py --folder roaming/x86-64/qemu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
