---

stages:
  - build
  - test
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  PHOSH_IMAGE_BRANCH: main
  PHOSH_IMAGE_UPLOAD_OPTS: --verbose
  LINT_DEPS: black flake8 markdownlint mypy

default:
  timeout: 36 hours
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

build:dev:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    ARCH: amd64
    VARIANT: development
  script:
    - XDG_CACHE_HOME=~/.cache make clean bengalos-${ARCH}-${VARIANT}
    - |
      if [ -n "${PHOSH_IMAGE_HOST}" ] && \
         [ -n "${PHOSH_IMAGE_UPLOAD}" ] && \
         [ "${CI_COMMIT_BRANCH}" = "${PHOSH_IMAGE_BRANCH}" ]; then
        ls -lh build-${ARCH}-${VARIANT}/BengalOS_*
        time make ARCH="${ARCH}" VARIANT=development IMAGE_HOST="${PHOSH_IMAGE_HOST}" upload
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi

build:immutable:nightly:amd64:
  stage: build
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    ARCH: amd64
    VARIANT: immutable
    AWS_ACCESS_KEY_ID: $PUSH_KEY
    AWS_SECRET_ACCESS_KEY: $PUSH_SECRET
  script:
    - XDG_CACHE_HOME=~/.cache make clean bengalos-${ARCH}-${VARIANT}
    - |
      if [ -n "$AWS_ENDPOINT_URL" ]; then
        time ./helpers/pack.sh
      else
        echo "Skipping upload on ${CI_COMMIT_BRANCH}."
      fi
  artifacts:
    paths:
      - build-amd64-immutable/*/hash

test:immutable:nightly:amd64:
  stage: test
  tags: ["phosh-images"]
  resource_group: phoshimages
  needs:
    - job: build:immutable:nightly:amd64
      artifacts: true
  script:
    - |
      rm -f *.qcow2
      HASH=$(awk '{ print $1 }' build-amd64-immutable/*/hash | head -n 1)
      echo "Testing ${HASH}"
      time ./helpers/get-qcow2.sh --hash "${HASH}"
      helpers/smoke-test-vm.sh --name "${HASH}" --disk *.qcow2
  artifacts:
    paths:
      - build-amd64-immutable/*/hash

publish:immutable:nightly:amd64:
  stage: publish
  tags: ["phosh-images"]
  resource_group: phoshimages
  variables:
    AWS_ACCESS_KEY_ID: $BLESS_KEY
    AWS_SECRET_ACCESS_KEY: $BLESS_SECRET
  needs:
    - job: test:immutable:nightly:amd64
      artifacts: true
  script:
    - |
      HASH=$(awk '{ print $1 }' build-amd64-immutable/*/hash | head -n 1)
      echo "Blessing ${HASH}"
      helpers/bless.sh --hash "${HASH}"
  artifacts:
    paths:
      - build-amd64-immutable/*/hash
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_PATH == "BengalOS-team/bengalos-recipes" && $CI_PIPELINE_SOURCE == "schedule"'

lint:
  stage: test
  needs: []
  image: 'godiug/website:v0.0.2025-09-14'
  script:
    - apt-get update
    - apt-get -y install $LINT_DEPS
    - make lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        paths:
          - "*.md"
          - "docs/*.md"
