[Distribution]
Distribution=debian
Release=forky

[Output]
ImageId=BengalOS
Format=disk
SplitArtifacts=uki,partitions,os-release
ManifestFormat=json

[Content]
UnifiedKernelImageFormat=%i_%v_%a
Bootable=true
WithRecommends=true
Packages=
        bengalos-base
        systemd-boot-efi

RootPassword=root
Splash=/usr/share/systemd/bootctl/bengalos-splash.bmp
KernelCommandLine=
        quiet
        splash
        plymouth.ignore-serial-consoles
        systemd.firstboot=off

ExtraTrees=../splash:/usr/share/systemd/bootctl/
