[Build]
ToolsTree=yes
ToolsTreeDistribution=debian
ToolsTreeRelease=forky
ToolsTreePackages=
        systemd-tpm

[Distribution]
Distribution=debian
Release=forky
Repositories=
        contrib
        non-free-firmware

[Output]
ImageId=BengalOS
Format=disk
SplitArtifacts=uki,partitions,os-release,kernel-modules-initrd
ManifestFormat=json
OutputDirectory=mkosi.output

[Content]
UnifiedKernelImageFormat=%i_%v_%a
Bootable=true
WithRecommends=true
WithDocs=false
#BaseTrees=%O/base_%v
# Keep Packages in sync with mkosi.image/base until
# https://github.com/systemd/mkosi/issues/4397 is fxed
# and we can use BaseTrees.
Packages=
        # TODO: pull in via bengalos-base
        apparmor
        bengalos-base
        systemd-boot-efi

RootPassword=root
Splash=/usr/share/systemd/bootctl/bengalos-splash.bmp
InitrdProfiles=plymouth
InitrdPackages=
        bengalos-initramfs

KernelCommandLine=
        quiet
        splash
        plymouth.ignore-serial-consoles
        systemd.firstboot=off

ExtraTrees=../splash:/usr/share/systemd/bootctl/
