[Distribution]
Distribution=debian
Release=forky

[Output]
ImageId=BengalOS
Format=disk

[Content]
Bootable=true
WithRecommends=true
Packages=
   alsa-ucm-conf
   alsa-utils
   apt
   apt-utils
   bluetooth
   busybox
   ca-certificates
   callaudiod
   dosfstools
   e2fsprogs
   file
   hwdata
   inetutils-ping
   iptables
   iw
   kbd
   libspa-0.2-bluetooth
   locales
   login
   mmc-utils
   network-manager
   openssl
   passwd
   phosh-full
   phosh-phone
   phosh-tablet
   phrog
   plymouth-theme-phosh
   pipewire-audio
   rfkill
   rtkit
   sudo
   systemd
   systemd-boot
   systemd-resolved
   usb-modeswitch
   usbutils
   wireless-regdb
   wireless-tools
   wireplumber
   wpasupplicant

RemovePackages=
   gnome-software-plugin-deb
   gnome-user-docs
   packagekit
   x11-xserver-utils

KernelCommandLine=
   quiet
   splash
