[Content]
Packages=systemd-boot-efi
         systemd-homed
         systemd-ukify
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=BengalOS-*:usr-verity=BengalOS-*:usr-verity-sig=BengalOS-*:root=BengalOS-*:home=BengalOS-*
        systemd.log_level=debug

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
