[Content]
Packages=
        systemd-container
        systemd-homed
        systemd-ukify
        podman-toolbox
# We use dissecting to find the partition, thus disable usrhash based lookup
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=unprotected+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=%i-%v:usr-verity=%i-%v-v:usr-verity-sig=%i-%v-vs:root=%i-root:home=%i-home
        usrhash=

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
