[Build]
Environment=
        BOS_DEVICE=sdm845

[Include]
# Use the device-qcom profile as base
Include=../device-qcom

[Content]
Packages=
        bengalos-kernel-sdm845

Devicetrees=
        qcom/sdm845-google-*.dtb

[Output]
# Usually UFS with 4k blocks is used.
SectorSize=4096
