[UKIProfile]
Profile=
	ID=Debug
	TITLE=Verbose Boot

Cmdline=
	debug
	plymouth.enable=0
	systemd.log_level=debug
	systemd.log_target=console
	# Can be useful to debug boot problems
	# rd.systemd.break=pre-switch-root
