[Config]
Dependencies=base

[Output]
Output=%i-%I_%v
Format=sysext
Overlay=yes
ImageId=%i

[Content]
BaseTrees=%O/base_%v
# TODO: Use a bengalos-dev package
Packages=
        debuginfod
        gdb
        strace
        systemd-coredump

[Validation]
# TODO: use signed if mkosi.crt is in kernel keyring
Verity=hash
