[Build]
Environment=
        BOS_DEVICE=sdm670

[Include]
# Use the device-arm64 profile as base
Include=../device-arm64

[Content]
Packages=
        bengalos-hw-support-qcom
        bengalos-firmware-sdm670
        linux-image-7.0.10-sdm670-g06f3bc759bf5

KernelCommandLine=
        # We currently have no secure boot on qcom and only produce immutable
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=unprotected:root=unprotected+absent:home=unprotected+absent:=ignore
        # Droid-juicer respects this too:
        firmware_class.path=/var/lib/firmware/

Devicetrees=qcom/sdm670-google*.dtb

# Ignore modules that need firmware in the initramfs
KernelInitrdModules=
        default
        -/drivers/bluetooth/
        -/drivers/media/platform/qcom/venus/
        -/drivers/net/ipa
        -/drivers/net/wireless/ath
        -/drivers/remoteproc/

InitrdPackages=
        bengalos-firmware-sdm670
        bengalos-hw-support-qcom-initramfs
        firmware-qcom-soc