[Build]
Environment=
        BOS_DEVICE=sdm670

[Include]
# Use the device-qcom profile as base
Include=../device-qcom

[Content]
Packages=
        bengalos-kernel-sdm670

Devicetrees=qcom/sdm670-google*.dtb

